### ISSUE TITLE
Example comparing global get to transaction address?

### ISSUE THREAD

**Issue by runvnc** [pzbitskiy/tealang#12]
Sorry to bother you again.  I am trying to use apps[0].get or apps[0].getEx.  Tried both, not able to check if that storage value matches the txn.Sender.

```
let ok, creator = apps[0].getEx("Creator")
let sentByCreator = txn.Sender == creator
```

..gives me:

```
error at app.tl line 26, col 5 near token "sentByCreator"
    let sentByCreator = txn.Sender == creator
   -----^-----
incompatible types: 'byte[]' vs 'uint64' in expr 'txn.Sender
 == ident creator'
```

I also tried with apps[0].get() and that one was a similar error except it said it was 'unknown'.

```
let creator = apps[0].get("Creator")
```

```
 let sentByCreator = txn.Sender == creator
   -----^-----
incompatible types: 'byte[]' vs 'unknown' in expr 'txn.Sender
 == ident creator'
```

Is there a way to indicate whether that app_global_get is supposed to be a byte[] or a uint?  Or maybe there is something more basic I am doing wrong.

Thanks for your time.

**Comment by runvnc** [comment]
Nevermind, works if I just put it in the `if` for some reason.
```
function handleUpdateEscrow() {
    //let creator = apps[0].get("Creator")
        let isUpdate = txn.OnCompletion == AcUpdateApplication
        //let sentByCreator = (txn.Sender == apps[0].get("Creator"))
        let hasOneArg = txn.NumAppArgs == 1
        let singleTransaction = global.GroupSize == 1
        if singleTransaction && isUpdate && (apps[0].get("Creator")==txn.Sender) && hasOneArg {
                apps[0].put("Escrow", txn.ApplicationArgs[0])
                return 1
        }
        return 0
}
```

**Comment by pzbitskiy** [comment]
I think this is because some examples need to updates - we have a bug in langspec.json where return types for app_local_getex were swapped. I’ll take a look.
