### ISSUE TITLE
Implement type cast

### ISSUE THREAD

**Issue by pzbitskiy** [pzbitskiy/tealang#15]
Use case:
`get` or `getEx` return either uint64 or []byte and there is no way to know.

Solution:
Implement "fake" type cast functions `uint64` and `bytes` to switch variable type.

The following should work:
```
let a = accounts[0].get("key") // unknown type
let b = uint64(a) + 1
a = uint64(a)
let c = a + b
```

**Comment by runvnc** [comment]
Is there a workaround for this? If I use something like `btoi(itob( apps[0].get("mynum") ))` the compile works, but not sure if it will give the right answer, and obviously adds a lot of instructions.
