### ISSUE TITLE
Adding 4 numbers = wrong answer?

### ISSUE THREAD

**Issue by runvnc** [pzbitskiy/tealang#25]
Hello, so towards the end of my program I am trying to sum 4 numbers.  The number was coming out wrong. And I keep trying to do it a slightly different way and getting different answers, some too high and some too low.

**Comment by pzbitskiy** [comment]
A code would be helpful. This is might be the same issue with variable allocation in nested functions as #21. I'll take a look into it.

**Comment by runvnc** [comment]
OK trying a test to see if isolating it makes a difference and try to get a minimum demo.

**Comment by runvnc** [comment]
I am 90% sure its the same issue because when I use 4 constants rather than local variables it works correctly.

**Comment by runvnc** [comment]
I think it may only happen when I try to return something from a function call.
