### ISSUE TITLE
Project going forward?

### ISSUE THREAD

**Issue by runvnc** [pzbitskiy/tealang#26]
Hello, I am guessing you were busy working on AVM 1 or something. Which by the way is one of the biggest updates to a platform I have ever seen. But anyway, are you planning on continuing to work on Tealang and upgrading it to allow the new capabilities? 

I heard something about an LLVM project that would make Algorand accessible from lots of languages or something.  Don't know if something related to that has now superceded Tealang. But to me Tealang is still the best option for the previous version features.

**Comment by algorandskiy** [comment]
Hello, yes, I remember I need to fix the variables allocation and add AVM 1.0 support, but not sure if I have time before end of Dec.

**Comment by runvnc** [comment]
Ok well I appreciate all of your efforts and know you are busy. Will be
happy to see the project continue whenever you get back to it. And I think
the Algorand community will benefit greatly if they find out about this
project.

**Comment by pzbitskiy** [comment]
v4 just released, v5 is under way!
