### ISSUE TITLE
TEAL v5

### ISSUE THREAD

**Issue by algoidurovic** [pzbitskiy/tealang#29]
Opcodes (these are the ops introduced in v5 but supporting all of them may not be necessary):
- [x] ed25519verify (now available in stateful programs)
- [x] ecdsa_verify, ecdsa_pk_decompress, ecdsa_pk_recover (for k1 curve)
- [ ] loads, stores (scratch slot index is top of stack)
- [ ] cover, uncover
- [x] extract, extract3, extract_uint16, extract_uint32, extract_uint64
- [x] app_params_get
- [x] log
- [x] itxn_begin, itxn_field, itxn_submit, itxn, itxna (inner transactions)
- [x] txnas, gtxnas, gtxnsas, args (dynamic indexing)

Transaction fields:
- [x] Logs
- [x] NumLogs
- [x] CreatedApplicationID
- [x] CreatedAssetID
- [x] Nonparticipation

Global fields:
- [x] CurrentApplicationAddress
- [x] GroupID

**Comment by algorandskiy** [comment]
`loads`, `stores` are detached to #31
`cover`, `uncover` are AVM stack manipulation and the stack is abstracted by tealang.
