### ISSUE TITLE
TEAL v6

### ISSUE THREAD

**Issue by algoidurovic** [pzbitskiy/tealang#30]
Opcodes (these are the ops introduced in v6 but supporting all of them may not be necessary):
- [x] acct_params_get
- [x] bsqrt, divw
- [x] itxn_next, gitxn, gitxna (inner transactions)
- [x] ~~gloadss (dynamic indexing)~~ (scratch space access)
- [x] itxnas, gitxnas (dynamic indexing)

Transaction fields:
- [x] LastLog
- [x] StateProofPK

Global fields:
- [x] OpcodeBudget
- [x] CallerApplicationID
- [x] CallerApplicationAddress

**Comment by algorandskiy** [comment]
`gloadss` is detached to #31

**Comment by pzbitskiy** [comment]
`itxnas` supported at #40
